mkdir -p ./assets/ycb_models
mkdir -p ./projects
mkdir -p ./lib
mkdir -p ./weights_emb
mkdir -p ./datasets/dataset_subset
mkdir -p ./datasets/dataset_cache
mkdir -p ./datasets/raw/ho3d
mkdir -p ./datasets/raw/yt3dhands
mkdir -p ./datasets/raw/nerf_synthetic
mkdir -p ./datasets/raw/xucong_hands
mkdir -p ./datasets/raw/freihand
mkdir -p ./datasets/raw/synthHands
mkdir -p ./datasets/raw/epic_kitchens
mkdir -p ./datasets/raw/shapenet
mkdir -p ./datasets/raw/egodexter
mkdir -p ./datasets/raw/ego3dhands
mkdir -p ./datasets/raw/obman
mkdir -p ./datasets/raw/fhad
